// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB42XW9KCt6NrD0jYyz_HjS806j2uMS9GE',
    appId: '1:666237418426:android:0c6fc4b0ca8ecb43bffb83',
    messagingSenderId: '666237418426',
    projectId: 'chatbot-d7259',
    databaseURL: 'https://chatbot-d7259-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-d7259.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo1RC2BbAqhJ0vnCrqjgWGJ7c7ATWS4rg',
    appId: '1:666237418426:web:bf80770365ea10b9bffb83',
    messagingSenderId: '666237418426',
    projectId: 'chatbot-d7259',
    authDomain: 'chatbot-d7259.firebaseapp.com',
    databaseURL: 'https://chatbot-d7259-default-rtdb.firebaseio.com',
    storageBucket: 'chatbot-d7259.appspot.com',
    measurementId: 'G-36EB6319NQ',
  );

}